Add man page to automake install, add nexpm to automake install, add exemplar Gentoo ebuild file

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -677,6 +677,7 @@ am__untar
 MAINTAINER_MODE_TRUE
 MAINTAINER_MODE_FALSE
 MAINT
+LN
 CP
 CC
 CFLAGS
@@ -705,6 +706,9 @@ VTWM_CFLAGS
 VTWM_LIBS
 xpm_CFLAGS
 xpm_LIBS
+ENABLE_NEXPM
+ENABLE_NEXPM_TRUE
+ENABLE_NEXPM_FALSE
 png_CFLAGS
 png_LIBS
 regex_CFLAGS
@@ -1361,6 +1365,7 @@ Optional Features:
 			  (and sometimes confusing) to the casual installer
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --disable-nexpm         Turn off nexpm building
   --disable-spacing       Turn off font height dependent text layout spacing
   --disable-opacity       Turn off _NET_WM_WINDOW_OPACITY client window
                           property support
@@ -2345,6 +2350,46 @@ fi
 
 
 ac_config_headers="$ac_config_headers config.h"
+
+
+# Extract the first word of "ln", so it can be a program name with args.
+set dummy ln; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_LN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LN in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LN="$LN" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_LN="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+LN=$ac_cv_path_LN
+if test -n "$LN"; then
+  { echo "$as_me:$LINENO: result: $LN" >&5
+echo "${ECHO_T}$LN" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
 
 
 # Extract the first word of "cp", so it can be a program name with args.
@@ -4263,6 +4308,14 @@ echo "${ECHO_T}yes" >&6; }
 	:
 fi
 
+# Check whether --enable-nexpm was given.
+if test "${enable_nexpm+set}" = set; then
+  enableval=$enable_nexpm; if test "$enable_nexpm" = "yes"; then ENABLE_NEXPM=yes; fi
+else
+  ENABLE_NEXPM=yes
+fi
+
+
 if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xpm\"") >&5
   ($PKG_CONFIG --exists --print-errors "xpm") 2>&5
@@ -4377,9 +4430,18 @@ echo "${ECHO_T}yes" >&6; }
 	:
 fi
 else
-  xpm_CFLAGS=-DNO_XPM_SUPPORT
+  xpm_CFLAGS=-DNO_XPM_SUPPORT; unset ENABLE_NEXPM
 fi
 
+
+
+ if test x$ENABLE_NEXPM = xyes; then
+  ENABLE_NEXPM_TRUE=
+  ENABLE_NEXPM_FALSE='#'
+else
+  ENABLE_NEXPM_TRUE='#'
+  ENABLE_NEXPM_FALSE=
+fi
 
 
 if test -n "$PKG_CONFIG" && \
@@ -6359,6 +6421,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${ENABLE_NEXPM_TRUE}" && test -z "${ENABLE_NEXPM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_NEXPM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_NEXPM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -6953,6 +7022,7 @@ am__untar!$am__untar$ac_delim
 MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
 MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 MAINT!$MAINT$ac_delim
+LN!$LN$ac_delim
 CP!$CP$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
@@ -6981,13 +7051,12 @@ VTWM_CFLAGS!$VTWM_CFLAGS$ac_delim
 VTWM_LIBS!$VTWM_LIBS$ac_delim
 xpm_CFLAGS!$xpm_CFLAGS$ac_delim
 xpm_LIBS!$xpm_LIBS$ac_delim
+ENABLE_NEXPM!$ENABLE_NEXPM$ac_delim
+ENABLE_NEXPM_TRUE!$ENABLE_NEXPM_TRUE$ac_delim
+ENABLE_NEXPM_FALSE!$ENABLE_NEXPM_FALSE$ac_delim
 png_CFLAGS!$png_CFLAGS$ac_delim
 png_LIBS!$png_LIBS$ac_delim
 regex_CFLAGS!$regex_CFLAGS$ac_delim
-regex_LIBS!$regex_LIBS$ac_delim
-TWM_USE_SPACING!$TWM_USE_SPACING$ac_delim
-TWM_USE_OPACITY!$TWM_USE_OPACITY$ac_delim
-TWM_USE_SLOPPYFOCUS!$TWM_USE_SLOPPYFOCUS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7029,6 +7098,10 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+regex_LIBS!$regex_LIBS$ac_delim
+TWM_USE_SPACING!$TWM_USE_SPACING$ac_delim
+TWM_USE_OPACITY!$TWM_USE_OPACITY$ac_delim
+TWM_USE_SLOPPYFOCUS!$TWM_USE_SLOPPYFOCUS$ac_delim
 NO_BUILD_INFO!$NO_BUILD_INFO$ac_delim
 xft_CFLAGS!$xft_CFLAGS$ac_delim
 xft_LIBS!$xft_LIBS$ac_delim
@@ -7072,7 +7145,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
